project:
  type: website
  output-dir: docs

website:
  title: "Learning - FoamTree"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: observable-reactable-demo.qmd
        text: "Observable Reactable Demo"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
